### ISSUE TITLE
GLCM - Information Measures of Correlation?

### ISSUE THREAD

**Issue by ejulrich** [Radiomics/pyradiomics#400] opened 2018-07-23 17:55 UTC
I wanted to find the background of the Gray Level Co-occurrence Matrix "[Informal Measures of Correlation](https://github.com/Radiomics/pyradiomics/blob/master/radiomics/glcm.py#L519)", and I had a lot of trouble finding the term. Were these supposed to be called the "Information Measures of Correlation"? [1]

[1] Haralick, et al. [Textural features for image classification.](http://haralick.org/journals/TexturalFeaturesHaralickShanmugamDinstein.pdf#page10) (1973).

**Comment by fedorov** [comment] 2018-07-23 18:14
@ejulrich I think you are right. IMC1 and IMC2 seem to correspond to First and Second measures of information correlation, as defined in 3.6.24 and 3.6.25 of [the IBSI v6 document](https://arxiv.org/abs/1612.07003). I think this is a bug. Let's wait for @JoostJM to get back to address this.

**Comment by fedorov** [comment] 2018-07-23 18:15
And I can't figure out why the equations are not rendered correctly for those in readthedocs!

https://pyradiomics.readthedocs.io/en/latest/features.html?highlight=imc#radiomics.glcm.RadiomicsGLCM.getImc1FeatureValue

**Comment by JoostJM** [comment] 2018-08-07 08:16
The name is indeed a bug, it should be "informational measure of correlation". I'll also take a look at why the docs do not render correctly...

**Comment by JoostJM** [comment] 2018-08-08 06:13
> And I can't figure out why the equations are not rendered correctly for those in readthedocs!

There is no error in the formula, but a rather strange behaviour caused by the fact that "IMC" is highlighted...

**Comment by JoostJM** [comment] 2018-08-08 06:15
Typo fixed in 4ba909a.

**Closed by JoostJM** 2018-08-08 06:15 UTC
Labels: bug
