### ISSUE TITLE
Version 2.2.0 c code potential bug of calculating NGTDM and GLDM

### ISSUE THREAD

**Issue by mingxilei** [Radiomics/pyradiomics#512] opened 2019-08-02 19:32 UTC
Hi,

I calculated the texture matrices of the digital phantom of IBSI and Pyradiomics seems to give me incorrect NGTDM and GLDM.
Pyradiomics with version 2.1.2 or lower gave correct ones and matched the benchmark matrices, however.

Version 2.2.0:
NGTDM
[[[0. 0. 0. 0. 2. 3. 1. 5. 4. 6. 6. 5. 2. 2. 5. 3. 3. 2. 1.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 2. 0. 2. 6. 4. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 4. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
GLDM
[[[50.         40.32615352  1.        ]
  [ 1.          0.2         3.        ]
  [16.         20.38912656  4.        ]
  [ 7.         24.12700535  6.        ]]]

Version 2.1.2:
NGTDM
[[0. 0. 0. 0. 2. 2. 1. 6. 4. 6. 5. 5. 3. 2. 5. 3. 3. 2. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 2. 6. 4. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 4. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
GLDM
[[50.         39.94695392  1.        ]
 [ 1.          0.2         3.        ]
 [16.         20.82540107  4.        ]
 [ 7.         24.12700535  6.        ]]

Please check. Thank you!

**Comment by fedorov** [comment] 2019-08-02 19:37
Thank you for the report! We will discuss when @JoostJM is back from vacation!

**Comment by JoostJM** [comment] 2019-08-12 12:35
@mingxilei Thanks for the report! This was indeed an issue (and as such, still is for version 2.2.0), but has since been corrected in the latest version (fix is implemented by #500).

This bug was caused by PR #463, which changed the C-Extensions to allow for N-dimensional input arrays. This changed how PyRadiomics defines a neighbor when iterating over an image for the texture matrices. Here, PyRadiomics needs to check if the voxel indicated by the offset (for the current angle) is inside the range of the image (to prevent out-of-range and/or slicing errors). 

Before, this was done in a single `if` statement, checking all 3 dimensions. 
However, with N-Dimensional calculation, this is not possible, and the offset is checked and applied in a loop over all dimensions. If the check failed, the index of the neighbor (`j`) was set to -1 to signal "out-of-range" and the loop was halted. 

Then here comes the bug: after the loop, there is a check to see whether the voxel defined by index `j` is part of the ROI (i.e. "is a valid neighbor"): `if (j > 0 && mask[j])`. 
This of course needs to be `if (j >= 0 && mask[j])`, as index 0 is a valid index! It was not caught by PyRadiomics' continuous testing, voxel with index 0 is not part of the ROI in any of the test cases and and therefore it does not matter that voxel with j=0 is skipped. For the IBSI phantom, voxel at index 0 *is* part of the ROI and was therefore incorrectly skipped.

Now I also mentioned this error has since been corrected and this was done more or less accidentally. In PR #500 datatypes for many of the index variables was changed to `size_t`, which is unsigned, i.e. j = -1 would be invalid. The erroneous check has therefor been changed, with `j` set to `i` (which does not occur otherwise, as the offsets are forced to move in at least 1 dimension), and the check updated to `if (j != i && mask[j])`.

As a closing remark, this bug also affected the other feature classes, but will most likely be less apparent, due to matrix normalization.

**Closed by JoostJM** 2019-08-12 12:35 UTC
Labels: backlog
