### ISSUE TITLE
list assignment index out of range

### ISSUE THREAD

**Issue by abhinandanbatra** [Radiomics/pyradiomics#461] opened 2019-02-05 14:31 UTC
Hi, I have to analyze 45 sets of 3D images. Whenever I run the program I get an error 
list assignment index out of range. When I am running only 15 cases it runs fine. Will appreciate any help.

**Comment by JoostJM** [comment] 2019-02-06 09:01
Hi @abhinandanbatra, can you share some more information? What were the settings you used for PyRadiomics? What is the error message you received? Can you share the PyRadiomics log file?

**Comment by abhinandanbatra** [comment] 2019-02-06 14:37
Hi Joost, 
Here is the error message that I get 

> IndexError                                Traceback (most recent call last)
<ipython-input-4-6b15c3760c08> in <module>()
     26 #
     27 
---> 28             features[Case_id] = featureextractor.RadiomicsFeaturesExtractor(image, mask)
     29 
     30             extractor.disableAllFeatures()

IndexError: list assignment index out of range


Below are the settings that I am using
`settings = {}
print(settings)
settings['binWidth'] = 25
settings['resampledPixelSpacing'] = None
# settings['resampledPixelSpacing'] = [3, 3, 3]  # This is an example for defining resampling (voxels with size 3x3x3mm)
settings['interpolator'] = 'sitkBSpline'
settings['correctMask'] = True

interpolator = settings.get('interpolator')
resampledPixelSpacing = settings.get('resampledPixelSpacing')
extractor = featureextractor.RadiomicsFeaturesExtractor(**settings)`

Also, there is one more issue that I came across, previously I was able to analyze the data but though I am getting all the results I am getting this message as well "Image/Mask geometry mismatch, attempting to correct Mask" for all the cases. I checked the dimensions, size and slice of mask and main image, they are totally same. I am not sure why I keep on getting this message

>

**Comment by JoostJM** [comment] 2019-02-06 15:54
`---> 28 features[Case_id] = featureextractor.RadiomicsFeaturesExtractor(image, mask)`

This line is where your error originates. As far as I can see, this appears to be in your own code.

1. How are `features` and `Case_id` in `features[Case_id]` defined? From the error, I assume `features` is a list. You cannot add an item by index in that way. Use `features.append()` instead.
1. `featureextractor.RadiomicsFeaturesExtractor(image, mask)`: This is an incorrect way of instantiating the extractor. For details on working with the feature extractor, see [this](https://pyradiomics.readthedocs.io/en/latest/usage.html#interactive-use) part of the documentation on interactive use. Alternatively, check out the [examples](https://github.com/Radiomics/pyradiomics/tree/master/examples), most specifically `helloRadiomics.py`.
1. Have you considered the CLI of PyRadiomics? This is also documented in the [Usage](https://pyradiomics.readthedocs.io/en/latest/usage.html) section of the documentation.

As to you other issue, regarding the geometry mismatch. Try logging with debug level logging:
 - `--log-file pyradiomics.log --logging-level DEBUG` for logging to file
- `-v 5` for debug output to console
- interactively: `radiomics.setVerbosity(logging.DEBUG)`

PyRadiomics then provides information on exactly what the mismatch is.

**Comment by abhinandanbatra** [comment] 2019-02-06 20:27
Hi Joost, 

Thank you for your response. here is the code that I came up with to loop through image and mask of different cases
`for Case_id in range(1,45):
    path = '/Users/abhinandanbatra/Desktop/pyradiomics/Converted/Case_{}/'.format(Case_id)
    print(path)
    for main in os.listdir(path):
        if fnmatch.fnmatch(main,'*image.nii'):
            print(main)
            image=sitk.ReadImage(os.path.join(path,main))
#             print(type(image))
            print(("{}:{}".format("Image Dimensions",image.GetDimension())))
            print(("{}:{}".format("Image Size",image.GetSize())))
            SubjectImage=sitk.GetArrayFromImage(image)
            fig,ax=plt.subplots(nrows=1, ncols=2)
            ax[0].imshow((SubjectImage)[0,:,:], cmap="gray", interpolation='nearest')
            ax[0].set_title(main)
            SubjectImage=sitk.GetArrayFromImage(image)
    for screen in os.listdir(path):
        if fnmatch.fnmatch(screen,'*label.nii'):
            print(screen)
            mask=sitk.ReadImage(os.path.join(path,screen))
#             print(type(mask))
            print(("{}:{}".format("Mask Dimensions",mask.GetDimension())))
            print(("{}:{}".format("Mask Size",mask.GetSize())))
            Segmentationimage=sitk.GetArrayFromImage(mask)
            ax[1].imshow((Segmentationimage)[0,:,:], cmap="gray", interpolation='nearest')
            ax[1].set_title(screen)
#             

            features[Case_id] = featureextractor.RadiomicsFeaturesExtractor(image, mask)
            result = extractor.execute(image, mask)
            print('Result type:', type(result))  # result is returned in a Python ordered dictionary)
            print('')
            print('Calculated features for Case {}:'.format(main))
            Finalresult=six.iteritems(result)
            for key, value in Finalresult:
                print('\t', key, ':', value)
`

I am just looping through the case number. 

Regarding second question, I never had the issue with the data when I was analyzing in small batches but now I get geometry mismatch when I am analyzing all the data together. Here are the settings that I am using `settings = {}
print(settings)
settings['binWidth'] = 25
settings['resampledPixelSpacing'] = None
# settings['resampledPixelSpacing'] = [3, 3, 3]  # This is an example for defining resampling (voxels with size 3x3x3mm)
settings['interpolator'] = 'sitkBSpline'
settings['correctMask'] = True

interpolator = settings.get('interpolator')
resampledPixelSpacing = settings.get('resampledPixelSpacing')
extractor = featureextractor.RadiomicsFeaturesExtractor()`

**Comment by JoostJM** [comment] 2019-02-07 09:06
In your code, I still do not see where you declare `features`. In any case, based on your code, it should be a dictionary (i.e. `features = {}`). You can also choose an OrderedDict, which will preserve the ordering of your cases (i.e. `from collections import OrderedDict` and `features = OrderedDict()`). That should solve your indexing error (you cannot use indexing to assign to new indexes in a list, but you can do so in case of dictionaries).

As to your geometry error, there are still 3 possible sources for your geometry mismatch: spacing, direction and origin. Together with size and dimension, the must match between the image and the mask. Take care! In lots of cases where conversion of DICOM to Nrrd or Niftii fails, ITK sets the spacing, direction and origin to it's defaults.
If you run the extraction as I've shown above, you should get the necessary info to fix this error.

**Comment by abhinandanbatra** [comment] 2019-02-13 14:09
Hey Joost, 
Thank you for the help. I was able to run the feature extraction on all case ids. I am still not able to get the log file running. I used the example code listed on pyradiomics webpage but it keeps on giving me  error logging is not defined. 

Also, since I am running the feature extraction on 3D data. Is it possible to get features slice by slice?

**Comment by JoostJM** [comment] 2019-02-13 14:18
@abhinandanbatra, The easiest way to enable logging is by using the command line interface. There, add the switches `--log-file <FILE>` and `--logging-level <LEVEL>` to enable logging to a file. `<FILE>` should be a valid path (i.e. directories must exist, but the file can be a new file) and `<LEVEL>` a valid logging level (e.g. `DEBUG` or `INFO`).

If you want to enable logging in the interactive mode, check out this function: [`_configureLogging(self)`](https://github.com/Radiomics/pyradiomics/blob/master/radiomics/scripts/__init__.py#L382).

To make this function work, ensure you've imported the correct libraries:
```
import logging.config
import logging.handlers
```

**Comment by JoostJM** [comment] 2019-02-13 14:37
@abhinandanbatra, what do you exactly mean "slice by slice"? As in, 1 value for each feature on each slice of your ROI? That is not directly possible in PyRadiomics. If you want, you'd have to write a little python loop to update the label values, giving each slice of the ROI it's own unique value, then use that to extract features in PyRadiomics (run the `execute` function of the extractor for each slice, identifying it by it's unique value).

If you want features that are calculated using only in-plane neighbors, but still yielding a single value per feature for the entire ROI, check out the `force2D` function in the documentation.

**Comment by abhinandanbatra** [comment] 2019-02-13 14:49
Hey I was able to get a log file here is the output
Checking mask with label 1
Calculating bounding box
Image/Mask geometry mismatch, attempting to correct Mask
Resampling mask to image geometry
Checking ROI validity
Checking if label 1 is persent in the mask
Comparing physical space of bounding box to physical space of image
ROI bounds (image coordinate space): ((26.49999350139064, 65.49999794661757, -0.5000054092394094), (224.49994494574335, 192.50000573268284, 22.49999769290026))
ROI valid, calculating resampling grid
Resampling...
Checking minimum number of dimensions requirements (2)
Image and Mask loaded and valid, starting extraction
Creating image type iterator
Adding image type "Original" with custom settings: {}
Extracting features
Yielding original image
Calculating features for original image
Cropping to size [198 127  23]
Computing firstorder
Initializing feature class
First order feature class initialized
Calculating features
Calculated 1 bins for bin width 25 with edges: [ 0. 25.])
Features extracted

Not sure why I am getting image mask mismatch


Regarding "slice by slice", so I have a 3d image data set with 25 slices. I drew a region of interest on each of the slice, than I went ahead and created a mask for each slice by making all the values inside  region of interest as 1 and outside region of interest for 0. I did this for all the slices. So, I have a 3d image and 3d mask.  When I run pyradiomics, I believe it gives me features based on whole 3d data set combined. Correct? So my question was if I want to see the feature values for each slice, will it be possible to get it?

**Comment by abhinandanbatra** [comment] 2019-02-13 15:19
Hey the code was running fine and now all of sudden I have started getting this error message  

ValueError: Image/Mask geometry mismatch. Potential fix: increase tolerance using geometryTolerance, see Documentation:Usage:Customizing the Extraction:Settings:geometryTolerance for more information

**Comment by abhinandanbatra** [comment] 2019-02-13 22:52
I have one question about first order feature: entropy. We are using Dixon fat fraction images for texture analysis but entropy values are always zero. Can you help me understand why this is happening? We previously analyzed the data using different software and results were different

**Comment by JoostJM** [comment] 2019-02-15 09:11
@abhinandanbatra, as mentioned above, set each slice to a different value inside the ROI (i.e 1, 2, 3, etc). Then use pyradiomics to extract features for each slice, keeping everything the same with the exception of "Label", which should be set to the value (again, 1, 2, 3, etc) corresponding to the slice you are extracting for.

As to your question on entropy; which entropy? firstorder? glcm? My first guess would be that your bin width is too large, resulting in a flat region after binning. This would result in an entropy 0. You can check this by logging with debug level and searching for: `D: radiomics.imageoperations: Calculated <N> bins for bin width <BW> with edges: [ ... ]`

Side note: This is already apparent from the log file you shared: `Calculated 1 bins for bin width 25 with edges: [ 0. 25.])`

**Comment by JoostJM** [comment] 2019-02-15 09:23
To get additional information on the image mask mismatch, try the following:

```
import SimpleITK as sitk

im = sitk.ReadImage('<path/to/image>')
ma - sitk.ReadImage('<path/to/mask>')

print(im)
print(ma)
```

**Comment by abhinandanbatra** [comment] 2019-02-19 14:43
@JoostJM , 
Thank you for the recommendations. I will work on your suggestions today or tomorrow and will let you know. I was asking about first order entropy. I think bin width is the issue. I will reduce the bin width and see if it helps. Thank you

**Comment by abhinandanbatra** [comment] 2019-02-21 21:09
@JoostJM I tried changing the bin width but it still gives me first order entropy of -0.0. Also, I went ahead and compiled the information regarding image and mask mismatch, they both are same. I dont know why I am getting this error of mismatch. Here is what I get after printing information for image and mask. Will appreciate your help on both these issues

**Image (0x7fd0628a0de0)**
  RTTI typeinfo:   itk::Image<float, 3u>
  Reference Count: 1
  Modified Time: 159991
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 159968
  UpdateMTime: 159990
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  Spacing: [0.486111, 0.486111, 5]
  Origin: [-142.065, 36.2373, -27.8908]
  Direction: 
1 0 0
0 -0.990944 -0.134278
0 -0.134278 0.990944

  IndexToPointMatrix: 
0.486111 0 0
0 -0.481709 -0.671391
0 -0.0652741 4.95472

  PointToIndexMatrix: 
2.05714 0 0
0 -2.03851 -0.27623
0 -0.0268556 0.198189

  Inverse Direction: 
1 0 0
0 -0.990944 -0.134278
0 -0.134278 0.990944

  PixelContainer: 
    ImportImageContainer (0x7fd0628a1070)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, float>
      Reference Count: 1
      Modified Time: 159987
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x12b5a5000
      Container manages memory: true
      Size: 2073600
      Capacity: 2073600



**Mask (0x7fd063399f40)**
  RTTI typeinfo:   itk::Image<unsigned char, 3u>
  Reference Count: 1
  Modified Time: 160182
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 160159
  UpdateMTime: 160181
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [288, 288, 25]
  Spacing: [0.486111, 0.486111, 5]
  Origin: [-142.065, 36.2373, -27.8908]
  Direction: 
1 0 0
0 -0.990944 -0.134278
0 -0.134278 0.990944

  IndexToPointMatrix: 
0.486111 0 0
0 -0.481709 -0.671391
0 -0.065274 4.95472

  PointToIndexMatrix: 
2.05714 0 0
0 -2.03851 -0.276229
0 -0.0268556 0.198189

  Inverse Direction: 
1 0 0
0 -0.990944 -0.134278
0 -0.134278 0.990944

  PixelContainer: 
    ImportImageContainer (0x7fd06338a3f0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 160178
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x1331f2000
      Container manages memory: true
      Size: 2073600
      Capacity: 2073600

**Comment by JoostJM** [comment] 2019-02-22 13:40
@abhinandanbatra they do look the same indeed... You can try to exactly recreate the PyRadiomics mask check by doing the following (in addition to the code above):

```
lsif = sitk.LabelStatisticsImageFilter()
lsif.Execute(im, ma)
```

If there is a geometry mismatch, this function should throw an error. If not, please check if you image and mask are indeed the ones that are passed to PyRadiomics (and it does not mix up 2 patients somewhere). If `lsif` does not throw an error, this is most likely the cause.

As to your entropy being 0.0, check the log file to see how many bins were created. You can also check firstoder_Range, this should give you some ideas on the what binWidth would be valid.

**Comment by JoostJM** [comment] 2019-02-22 13:43
This is the part of the code that is throwing your error: 

https://github.com/Radiomics/pyradiomics/blob/master/radiomics/imageoperations.py#L194

Reading it, I can see there is a possibility that SimpleITK is throwing a different error, but it still tries to resample the mask. Let me know what you find out.

**Comment by abhinandanbatra** [comment] 2019-02-22 13:48
@JoostJM thank you so much, I will go through the code. Also, regarding my other questions I was able to find issue with entropy. Actually the pixel value in the image I am using is between 0 and 1. Due to which bin width of 25 I am currently using is too high. Can you recommend on how should I select the bin width?

**Comment by JoostJM** [comment] 2019-02-22 14:03
@abhinandanbatra, I'd guess somewhere between 0.01 and 0.1 (binWidth is a float value, so can be smaller than 1). See the FAQ section in the documentation on some tips on working with the bin width.

**Closed** 2019-03-27 09:28 UTC
